#!/usr/bin/env bash
# Fix Nginx user and port in 5 lines.
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-enabled/default
service nginx restart
