#!/usr/bin/env bash
# This script installs and configures Nginx to serve a custom page on port 80.

# Update the package index
apt-get update -y

# Install nginx (if not already installed)
apt-get install nginx -y

# Create a custom index.html file
# This will overwrite the default Nginx page
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart the Nginx service to apply changes
# Using init.d as systemctl is not allowed
/etc/init.d/nginx restart

exit 0
